# Generated by Django 5.0.3 on 2024-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_failedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedmessage',
            name='chat_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedmessage',
            name='text',
            field=models.CharField(default='asdf', max_length=5000, unique=True),
            preserve_default=False,
        ),
    ]
