# Generated by Django 5.0.3 on 2024-03-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedmessage',
            old_name='reply_markup',
            new_name='inline_keyboard',
        ),
    ]
