# Generated by Django 5.0.3 on 2024-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_reply_markup_failedmessage_inline_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedmessage',
            name='error_message',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
